[Chore] husky, commitlint (#8) (#11)
* 📦 Chore: husky 설치 및 설정

* 📦 Chore: husky 세팅 및 commitlint 설정 적용

* 🐛 Bug: github repo 가상환경에서 발생하는 노드 버전 이슈 해결

* 🐛 Bug: feat/** 적용되도록 수정

* 🐛 Bug: node.js 버전 16 -> 20

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,13 +1,11 @@
-#!/bin/sh
+echo ">> Husky: Pre-commit hook"
+echo ">> Running linting..."
 
-# Enable colors in Powershell (has scrolling issue?)
-export FORCE_COLOR=1
+npx.cmd lint-staged
 
-# Fix scrolling issue
-exec >/dev/console 2>&1;
+if [ $? -ne 0 ]; then
+  echo ">> Linting failed. Aborting commit."
+  exit 1
+fi
 
-# Check changed files
-bun lint-staged
-
-# Build project
-bun run build
+echo ">> Linting passed!!"
